# Generated by Django 5.2.7 on 2025-10-05 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('setor_atual', models.CharField(blank=True, choices=[('UTI', 'UTI'), ('ENFERMARIA', 'Enfermaria'), ('APARTAMENTO', 'Apartamento')], max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo_cid', models.CharField(max_length=10, unique=True)),
                ('tempo_internacao_ideal', models.IntegerField(help_text='Tempo em dias')),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Patologias',
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('valor_padrao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedimentoPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_maxima', models.IntegerField(default=1)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('patologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos_padrao', to='core.patologia')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.procedimento')),
            ],
            options={
                'verbose_name_plural': 'Procedimentos Padrão',
                'unique_together': {('patologia', 'procedimento')},
            },
        ),
    ]
