# Generated by Django 5.2.7 on 2025-10-05 22:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Internacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('ALTA', 'Alta'), ('TRANSFERENCIA', 'Transferência')], default='ATIVA', max_length=20)),
                ('setor', models.CharField(choices=[('UTI', 'UTI'), ('ENFERMARIA', 'Enfermaria'), ('APARTAMENTO', 'Apartamento')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('alerta_tempo', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internacoes', to='core.paciente')),
                ('patologia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.patologia')),
            ],
            options={
                'verbose_name': 'Internação',
                'verbose_name_plural': 'Internações',
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONCORRENTE', 'Concorrente'), ('RETROSPECTIVA', 'Retrospectiva')], max_length=20)),
                ('data_auditoria', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacoes', models.TextField()),
                ('itens_glosados', models.IntegerField(default=0)),
                ('valor_glosado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('internacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='auditoria.internacao')),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
            },
        ),
        migrations.CreateModel(
            name='ItemConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('data_lancamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('GLOSADO', 'Glosado')], default='PENDENTE', max_length=20)),
                ('justificativa', models.TextField(blank=True)),
                ('internacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_conta', to='auditoria.internacao')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.procedimento')),
            ],
            options={
                'verbose_name': 'Item da Conta',
                'verbose_name_plural': 'Itens da Conta',
            },
        ),
    ]
